# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf411b5f4663bb35af2980bdcc7664469e5477b00c01aa7d2e597e183f4ce949cf6be87765a8cb20f1306498ee2a74707e7327974e66700f2008722959834f9f

test:
  secret_key_base: fea649e20e4b115abf6359189028f63be25182fa23ce429af7a3ce86d2c3633603611b6be69e5105e6208d1753bf5fc95ef50b6b4c15f846558aa692760764fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
